### ISSUE TITLE
`build` isn't working again

### ISSUE THREAD

**Issue by stbenjam** [openshift/ci-chat-bot#106]
I asked the bot:

```
build openshift/machine-config-operator#1972,openshift/machine-api-operator#632,openshift/installer#3929
```

It's launching release-openshift-origin-installer-launch-gcp: https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/release-openshift-origin-installer-launch-gcp/1291766374934253568

The bot responded to me with `job build openshift/machine-config-operator#1972,openshift/machine-api-operator#632,openshift/installer#3929 failed`, however that job is still running with no log output.

**Comment by cgwalters** [comment]
Probably a random CI blip, this works now right?

**Comment by stbenjam** [comment]
> Probably a random CI blip, this works now right?

Seems to be working now, thanks. FWIW, I did try twice :)

/close
