### ISSUE TITLE
Extend cluster uptime

### ISSUE THREAD

**Issue by lilic** [openshift/ci-chat-bot#35]
Currently, the default uptime is 2 hours, but for certain testing I would need to extend that by X minutes/hours. It would be nice to have a command to extend the lifecycle of the cluster by a certain amount of time. 

Another idea is to specify uptime ahead, so `launch 3h`. That would mean users can't indefinitely extend the cluster the same way they could in an already running cluster.

**Comment by smarterclayton** [comment]
Do you need indefinite?  What’s your estimated X?  How often do you need to do that?

**Comment by LiliC** [comment]
No don’t need indefinite.
Max 8 hours uptime.
My use case is if I spin up cluster, 2 hours is enough to reproduce a problem but not test the solution. So I need an extra hour or so to test it out, but then my cluster is down so need to spin up a new one, wait 30 minutes...

Curious if we have any data how often users spin a cluster and straight away after the cluster is shutdown they spin up a new one.

**Comment by paulfantom** [comment]
Could we have a command to extend cluster life by another 2 hours? This way we limit cost concerns by preserving old behaviour but still allow to have a longer running cluster when needed.

**Comment by smarterclayton** [comment]
We went to 3 hours and will continue to tweak up.  We're leaving the door open for more changes but not short term.
