### ISSUE TITLE
password appears empty when cluster is not ready

### ISSUE THREAD

**Issue by sarroutbi** [openshift/ci-chat-bot#418]
From my perspective, it makes no sense to show this message:

![image](https://github.com/openshift/ci-chat-bot/assets/959277/d0d4582b-f50b-40f8-ad2d-39bd90e42214)

It should only be shown once it is confirmed there is no error (cluster has been correctly launched). Otherwise, it can be confusing.

**Comment by AlexNPavel** [comment]
Hello. It appears that the main issue here is that the password is not set up correctly. The Cluster Bot sends the message as listed above when the cluster is ready, but the console (which is the web UI) is not. In these cases, the cluster should be ready to be interacted with via the `oc` tool, but not through a browser.

The password missing is a different issue that we should investigate. The cluster should always have a password by the time this message is sent.
