### ISSUE TITLE
rosa create {version} {duration} starts to have problems from this morning CET

### ISSUE THREAD

**Issue by danielemams** [openshift/ci-chat-bot#451]
Hi,

I use a lot of times Cluster Bot on Slack with the following command/message:

rosa create {version} {duration} 

example: rosa create 4.14.9 6h

From this morning CET I have the following response from Cluster Bot:

> rosa create 4.14.12 6h

> Failed to create cluster: Failed to run command: exit status 1

So after that I try with another rosa create command, changing the version:

> rosa create 4.14.9 6h

> you have already requested a cluster; 4 minutes have elapsed

And I need to do:

> done

> Cluster mzms4-nur3s-ynf successfully marked for deletion

So seems that the first create with 4.14.12 did something, because when I call done it answer me with a clusterName (mzms4-nur3s-ynf), but it response me with: "Failed to create cluster: Failed to run command: exit status 1".

And so I can not create anymore rosa cluster with Cluster Bot from this morning CET.

Why?

Thank you

**Comment by bradmwilliams** [comment]
There was an outage this morning that was preventing communication between AWS and OSD's environment.  That almost certainly was the case of your issue.  I see that you currently have a ROSA cluster provisioned now.

**Comment by danielemams** [comment]
Hi,

**Comment by danielemams** [comment]
Hi,
yes now seems works fine.
Thank you
