### ISSUE TITLE
rosa create failing with permission error

### ISSUE THREAD

**Issue by katheris** [openshift/ci-chat-bot#494]
I was able to successfully use the `rosa create` command on the 20th August, but at 8.50am BST on 21 August it is now failing with the following permission error:

Failed to create cluster: Failed to create cluster: Failed to check permission for creating security group: You are not authorized to perform this operation. User: arn:aws:sts::891590055837:assumed-role/ManagedOpenShift-HCP-ROSA-Installer-Role/OCM is not authorized to perform: ec2:CreateSecurityGroup on resource: arn:aws:ec2:us-east-1:891590055837:security-group/* with an explicit deny in a service control policy.

**Comment by bradmwilliams** [comment]
I do not see any indication that this is happening any longer.  These types of issues occasionally happen if/when ROSA updates their underlying roles and we need to manually recreate them with the updated versions.  Sorry for any inconvenience!

**Comment by katheris** [comment]
It is now working so I'll close this issue
