### ISSUE TITLE
Links to custom payloads are being misinterpreted

### ISSUE THREAD

**Issue by vrutkovs** [openshift/ci-chat-bot#53]
QE has been running `test upgrade  quay.io/openshift-release-dev/ocp-release:4.2.9  registry.svc.ci.openshift.org/ocp/release:4.3.0-0.nightly-2019-12-05-213858` a few times and chat bot didn't interpret the slack message correctly.

[Prow job](https://prow.svc.ci.openshift.org/prowjob?prowjob=chat-bot-2019-12-06-204629.8659) has been created but the release image param was `'<http://quay.io/openshift-release-dev/ocp-release:4.2.9|quay.io/openshift-release-dev/ocp-release:4.2.9> '` instead of just `quay.io/openshift-release-dev/ocp-release:4.2.9`

**Comment by smarterclayton** [comment]
Fixed now
