### ISSUE TITLE
`build` release image not accessible to regular api.ci user

### ISSUE THREAD

**Issue by stbenjam** [openshift/ci-chat-bot#69]
I asked the slack bot to create a release for me:

```
build openshift/machine-api-operator#502,openshift/cluster-autoscaler-operator#133
```

And it did: https://storage.googleapis.com/origin-ci-test/logs/release-openshift-origin-assemble/18/build-log.txt

However, I do not have access to the release with my api.ci  user:

```
$ oc adm release info --registry-config /home/notstack/pullsecret.json registry.svc.ci.openshift.org/ci-ln-gt0wv3b/release:latest 
error: unable to read image registry.svc.ci.openshift.org/ci-ln-gt0wv3b/release:latest: unauthorized: authentication required
```

I'm not the author of the PR's, but I also don't see any user being added to have access to that namespace.  I'd expect the requester to cluster-bot to have access, or even better, anyone with valid api.ci creds...

**Comment by smarterclayton** [comment]
Yeah.  Going to have to be all users because of mapping issues.
