### ISSUE TITLE
Build no longer working?

### ISSUE THREAD

**Issue by stbenjam** [openshift/ci-chat-bot#89]
I tried to kick-off a build, but I can't find the job in prow, and I never heard back from cluster-bot.

![image](https://user-images.githubusercontent.com/429763/81944785-39de6f80-95cb-11ea-8b64-fc6036f9f2ba.png)

**Comment by stbenjam** [comment]
Actually it did run but seemed to create an aws cluster which is different to how it worked before.

https://storage.googleapis.com/origin-ci-test/logs/release-openshift-origin-installer-launch-aws/11271/build-log.txt

CC: @smarterclayton

**Comment by smarterclayton** [comment]
Thanks, will look

**Comment by smarterclayton** [comment]
Yeah, this was a consequence of a job change.
